# -*- coding: utf-8 -*-
"""decisiontree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ooOGyI-HKBbYq9aKJt4Bl7vn-giEXSDU
"""

## Decision tree algorithm
from sklearn.datasets import load_iris
iris=load_iris()

x=iris.data
y=iris.target

## train test the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

x_train.shape

x_test.shape

## apply algorithm
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

## y pred
y_pred=dtc.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

## creating the actual tree
from sklearn.tree import plot_tree
from matplotlib.pylab import rcParams
rcParams['figure.figsize']=80,50
plot_tree(dtc,filled=True)