# -*- coding: utf-8 -*-
"""Eucladian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1anBAXM9MYMOx2kJU_f4qUim_Qkq_THDY
"""

## calculating the eucladian distance
import numpy as np
a=np.array([1,2])
b=np.array([4,5])

dist = np.linalg.norm(a - b)
print(dist)