# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NQv2uJpRu9Elp32MZr1_liyK26KwYQgu
"""

# Step 1: Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Step 2: Create a larger dataset (20 rows)
data = {
    "UserID": list(range(1, 21)),
    "Age": [22,25,27,30,32,35,37,40,42,45,
            48,50,52,55,57,60,62,65,67,70],
    "EstimatedSalary": [20000,25000,28000,35000,38000,45000,48000,52000,55000,60000,
                        65000,70000,72000,75000,78000,80000,85000,90000,95000,100000],
    "Gender": ["Male","Female","Female","Male","Male",
               "Female","Female","Male","Male","Female",
               "Female","Male","Female","Male","Male",
               "Female","Female","Male","Male","Female"],
    "Purchased": [0,0,0,0,0,1,1,1,1,1,
                  1,1,1,1,1,1,1,1,1,1]
}

df = pd.DataFrame(data)

# Step 3: Select features (Age, Salary) and target
x = df.iloc[:, 1:3].values   # Age + Salary
y = df.iloc[:, -1].values    # Purchased

# Step 4: Train/Test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

# Step 5: Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Step 6: Apply KNN
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(x_train, y_train)

# Step 7: Predictions
y_pred = classifier.predict(x_test)

# Step 8: Accuracy
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n", cm)
print("Accuracy:", acc)

