# -*- coding: utf-8 -*-
"""MultipleLR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17rR20gRgY69ByGJiKSh-_nRvzJN023Ya
"""

# Commented out IPython magic to ensure Python compatibility.
## Multiple LR
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# Create data

data = """cgpa,internships,projects,package
6.2,0,1,3.0
6.5,0,2,3.4
6.8,1,1,3.8
7.0,1,2,4.0
7.2,1,3,4.5
7.5,1,4,4.8
7.8,2,3,5.2
8.0,2,4,5.5
8.2,2,5,6.0
8.4,2,6,6.5
8.6,3,4,6.8
8.7,3,5,7.0
8.8,3,6,7.4
9.0,3,7,7.8
9.1,4,6,8.0
9.2,4,7,8.3
9.3,4,8,8.6
9.4,5,7,8.9
9.5,5,8,9.2
9.6,5,9,9.5
"""

# Save as CSV
with open("student_package.csv", "w") as f:
    f.write(data)

# Load into pandas
df = pd.read_csv("student_package.csv")
print(df.head())

df.shape

## Plot in 3d
import plotly.express as px
fig=px.scatter_3d(df,x='cgpa',y='internships',z='package',color='projects')
fig.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

x = df[['cgpa', 'internships', 'projects']]
y = df['package']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
print(mse)

r2_score=lr.score(x,y) ## tells model accuracy
print(r2_score)

lr.coef_

lr.intercept_